// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpc9sC9XKvdRPK3_GNGuWgbrQ2Eetnff4',
    appId: '1:605950703306:web:bd872315f7f1a360162633',
    messagingSenderId: '605950703306',
    projectId: 'tubesmobile-58757',
    authDomain: 'tubesmobile-58757.firebaseapp.com',
    storageBucket: 'tubesmobile-58757.firebasestorage.app',
    measurementId: 'G-G14L4RDTLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDAns7E0sZADhdseeH9MBwf1TSjCFZi4I',
    appId: '1:605950703306:android:8ad54cfa5fb4a244162633',
    messagingSenderId: '605950703306',
    projectId: 'tubesmobile-58757',
    storageBucket: 'tubesmobile-58757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3JfC-1_q8fb-Ah9m_lLFJkHnGc8byGW0',
    appId: '1:605950703306:ios:815fe93e79f6df1a162633',
    messagingSenderId: '605950703306',
    projectId: 'tubesmobile-58757',
    storageBucket: 'tubesmobile-58757.firebasestorage.app',
    iosBundleId: 'com.example.mobilebm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3JfC-1_q8fb-Ah9m_lLFJkHnGc8byGW0',
    appId: '1:605950703306:ios:815fe93e79f6df1a162633',
    messagingSenderId: '605950703306',
    projectId: 'tubesmobile-58757',
    storageBucket: 'tubesmobile-58757.firebasestorage.app',
    iosBundleId: 'com.example.mobilebm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpc9sC9XKvdRPK3_GNGuWgbrQ2Eetnff4',
    appId: '1:605950703306:web:bea600555ab74980162633',
    messagingSenderId: '605950703306',
    projectId: 'tubesmobile-58757',
    authDomain: 'tubesmobile-58757.firebaseapp.com',
    storageBucket: 'tubesmobile-58757.firebasestorage.app',
    measurementId: 'G-BBS64H45VY',
  );
}
